version: '3.7'

services:
  iris:
    image: andreasschneiderixdbde/openflights-iris
    ports:
      - "1972:1972"
  zeppelin:
    image: andreasschneiderixdbde/openflights-iris-zeppelin
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
      - ./notebook:/notebook
      - ./conf/interpreter.json:/zeppelin/conf/interpreter.json
    environment:
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_LOG_DIR: /logs
    depends_on:
      - iris
    links:
      - "iris:irisdb.openflights.com"